server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9080

logging:
  level: INFO
  loggers:
    se.citerus: DEBUG

  appenders:
    - type: console
